# Site Params
description = "DDLitLab – Digital and Data Literacy in Teaching Lab"
images = ['illustrations/hero/hero_adobe_main-hero.png']
mainMenuLogo = "illustrations/logo-site/favicon.png"

# For favicons
## Chrome Browser
themeColor = "#fff"

# Alert
alert = false
alertDismissable = true
alertText = "Introducing this new service! <a class=\"alert-link stretched-link\" href=\"https://salvus.site/\">Check out Total Security</a>"

# Pre-footer
footerAbout = true
footerAboutTitle = "Few Words About Us"
footerAboutText = "We protect your website so you can provide a safe environment to build trust and improve the user experience of your visitors.<br/><br/>Salvus Site is the partner that you can rely on for preventive and reactive cybersecurity."

[options]
  bootStrapJs = false
  breadCrumb = false
  listCategoryFilter = false
  listTagFilter = false

# Social Media Configuration
[Social]
  # twitter = "your_twitter_handle"  # Optional: Add your Twitter handle if you have one
