baseURL = '/'
languageCode = 'en-us'
title = 'DDLitLab'
theme = 'hugo-bootstrap-theme'
themesdir = 'node_modules/@filipecarneiro'

author = "Filipe Carneiro"
copyright = "Open-source <a class=\"text-muted text-decoration-none\" href=\"https://github.com/filipecarneiro/hugo-bootstrap-theme/blob/main/LICENSE\">MIT</a> Licensed."


[caches]
  [caches.images]
    dir = ':cacheDir/images'