baseURL = '/'
languageCode = 'en-us'
# title = 'DDLitLab'
# theme = 'ddlitlab'
# themesdir = 'themes/'

author = "David Jacobs"
copyright = "Open-source, what licence?"

license = "MIT"
licenselink = "https://github.com/filipecarneiro/hugo-bootstrap-theme/blob/main/LICENSE"

tags = ["bootstrap","minimal","responsive","modern","blog","landing page"]
features = ["security aware","fast by default","seo-ready","bootstrap framework","bootstrap 5","bootstrap 5.3"]

min_version = "0.123.0"

[caches]
  [caches.images]
    dir = ':cacheDir/images'


    