# [[main]]
# name = "Home"
# url = ""
# weight = 10

[[main]]
name = "Ringvorlesung Datenwelten"
url = "datenwelten"
weight = 20

[[main]]
name = "Lehrlabore"
url = "lehrlabore"
weight = 30

[[main]]
name = "Studi-Projekte"
url = "studi-projekte"
weight = 40

[[main]]
name = "GKI Community"
url = "gki-community"
weight = 50

[[main]]
name = "About"
url = "about"
weight = 60

[[social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='/hugo-bootstrap-theme/images/feather/feather-sprite.svg#github'/></svg>"
  url = "https://github.com/filipecarneiro/hugo-bootstrap-theme/"
  weight = 70
  title = "Visit the GitHub project"