[[main]]
name = "Data Worlds"
url = "datenwelten"
weight = 20

[[main]]
name = "Teaching Lab"
url = "lehrlabor"
weight = 30

[[main]]
name = "Student Projects"
url = "studiprojekte"
weight = 40

[[main]]
name = "GAI Community"
url = "gkicommunity"
weight = 50

[[main]]
name = "Teaching Navi"
url = "https://www.uni-hamburg.de/lehre-navi/lehrende.html"
weight = 60
pre = "<i class='codicon codicon-arrow-right' style='font-size: 1rem; transform: rotate(-45deg); display: inline-block; font-weight: 1000'></i>"

[[main]]
name = "About"
url = "about"
weight = 70