[[main]]
name = "Datenwelten"
url = "datenwelten"
weight = 20

[[main]]
name = "Lehrlabore"
url = "lehrlabore"
weight = 30

[[main]]
name = "Studi-Projekte"
url = "studiprojekte"
weight = 40

[[main]]
name = "GKI Community"
url = "gkicommunity"
weight = 50

[[main]]
name = "Lehre-Navi"
url = "https://www.uni-hamburg.de/lehre-navi/lehrende.html"
weight = 60
pre = "<i class='codicon codicon-arrow-right' style='font-size: 1rem; transform: rotate(-45deg); display: inline-block; font-weight: 1000'></i>"

[[main]]
name = "Über Uns"
url = "about"
weight = 70